"""Single file used for constants."""

BASE_COLS = {
    'player': 'Player Name',
    'team': 'Team',
    'position': 'Position',
    'age': 'Age',
    'club': 'Club',
    'cards_yellow': 'Yellow Cards',
    'cards_red': 'Red Cards',
    'minutes_per_game': 'Minutes per Game',
    'minutes_pct': 'Minutes Percentage',
    'minutes_per_start': 'Minutes per Start',
    'games_complete': 'Games Completed',
    'games_subs': "Games where Subbed On",
    'minutes_per_sub': 'Minutes Played After Substitution',
    'unused_subs': 'Unused Substitutions',
    'plus_minus': 'Plus/Minus',
    'plus_minus_per90': 'Plus/Minus per 90 Minutes',
    'plus_minus_wowy': 'Plus/Minus WOWY',
    'cards_yellow_red': 'Total Cards',
    'fouls': 'Number of Fouls',
    'fouled': 'Numer of Times Fouled',
    'pens_conceded': 'Penalties Conceded',
    'own_goals': 'Own Goals',
}

FIELD_PLAYER_COLS = {
    'minutes': 'Total Minutes Played',
    'minutes_90s': 'Overtime Minutes',
    'games': 'Games Played',
    'games_starts': 'Game Starts',
    'goals': 'Goals Scored',
    'assists': 'Assists',
    'goals_assists': 'Goals from Assists',
    'goals_pens': 'Goals from Penalties',
    'pens_made': 'Penalties Made',
    'pens_att': 'Penalties Attempted',
    'points_per_game': 'Point per Game',
    'on_goals_for': 'On Field During Goals For',
    'on_goals_against': 'On Field During Goals Against',
    'goals_per90': 'Goals per 90 Minutes',
    'assists_per90': 'Assists per 90 Minutes',
    'goals_assists_per90': 'Goals from Assists per 90 Minutes',
    'goals_pens_per90': 'Goals from Penalties per 90 Minutes',
    'goals_assists_pens_per90': 'Total Goals per 90 Minutes',
    'shots': 'Shots',
    'shots_on_target': 'Shots on Target',
    'shots_on_target_pct': 'Shot on Target Percentage',
    'shots_per90': 'Shots per 90 Minutes',
    'shots_on_target_per90': 'Shots on Target per 90 Minutes',
    'goals_per_shot': 'Goals per Shot',
    'goals_per_shot_on_target': 'Goals per Shot on Target',
    'offsides': 'Offsides',
    'crosses': 'Crosses',
    'interceptions': 'Interceptions',
    'tackles_won': 'Tackles Won',
    'pens_won': 'Penalties Won',
}

GOALKEEPER_COLS =  {
    'gk_games': 'Goalkeeper Games Played',
    'gk_games_starts': 'Starts',
    'gk_minutes': 'Goalkeeper Minutes Played',
    'gk_goals_against': 'Goals Scored Against',
    'gk_goals_against_per90': 'Goals Scored Against per 90 Minutes',
    'gk_shots_on_target_against': 'Shot on Target Against',
    'gk_saves': 'Saves',
    'gk_save_pct': 'Save Percentage',
    'gk_wins': 'Wins',
    'gk_ties': 'Ties',
    'gk_losses': 'Losses',
    'gk_clean_sheets': 'Clean Sheets',
    'gk_clean_sheets_pct':	'Clean Sheets Percentage',
    'gk_pens_att': 'Penalties Attempted On',
    'gk_pens_allowed': 'Penalties Allowed',
    'gk_pens_saved': 'Penalties Saved',
    'gk_pens_missed': 'Penalties Missed',
    'gk_pens_save_pct': 'Penalties Saved Percentage',
}

PLAYER_COLS = BASE_COLS | FIELD_PLAYER_COLS | GOALKEEPER_COLS
