import os
import psycopg2
from dotenv import load_dotenv

# Load the .env file generated by Neon
load_dotenv()

def test_neon():
    # Get connection string
    database_url = os.getenv("DATABASE_URL")

    try:
        # Connect to Neon
        conn = psycopg2.connect(database_url)
        cur = conn.cursor()

        # Run test query
        cur.execute("SELECT 1;")
        result = cur.fetchone()

        print(f"Connection successful! Result of 'SELECT 1;': {result[0]}")

        cur.close()
        conn.close()
    except Exception as e:
        print(f"Connection failed: {e}")
