CREATE SCHEMA worldcup26;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: images; Type: TABLE; Schema: worldcup26; Owner: -
--

CREATE TABLE worldcup26.images (
    id bigint NOT NULL,
    image_url character varying,
    player_id bigint NOT NULL
);


--
-- Name: images_id_seq; Type: SEQUENCE; Schema: worldcup26; Owner: -
--

ALTER TABLE worldcup26.images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME worldcup26.images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: players; Type: TABLE; Schema: worldcup26; Owner: -
--

CREATE TABLE worldcup26.players (
    player character varying(50),
    team character varying(50),
    team_country character varying(50),
    "position" character varying(50),
    age integer,
    birth_year integer,
    club character varying(50),
    games integer,
    games_starts integer,
    minutes real,
    minutes_90s real,
    goals real,
    assists real,
    goals_assists real,
    goals_pens real,
    pens_made real,
    pens_att real,
    cards_yellow real,
    cards_red real,
    goals_per90 real,
    assists_per90 real,
    goals_assists_per90 real,
    goals_pens_per90 real,
    goals_assists_pens_per90 real,
    shots real,
    shots_on_target real,
    shots_on_target_pct real,
    shots_per90 real,
    shots_on_target_per90 real,
    goals_per_shot real,
    goals_per_shot_on_target real,
    minutes_per_game real,
    minutes_pct real,
    minutes_per_start real,
    games_complete integer,
    games_subs integer,
    minutes_per_sub real,
    unused_subs integer,
    points_per_game real,
    on_goals_for real,
    on_goals_against real,
    plus_minus real,
    plus_minus_per90 real,
    plus_minus_wowy real,
    cards_yellow_red real,
    fouls real,
    fouled real,
    offsides real,
    crosses real,
    interceptions real,
    tackles_won real,
    pens_won real,
    pens_conceded real,
    own_goals real,
    gk_games real,
    gk_games_starts real,
    gk_minutes real,
    gk_goals_against real,
    gk_goals_against_per90 real,
    gk_shots_on_target_against real,
    gk_saves real,
    gk_save_pct real,
    gk_wins real,
    gk_ties real,
    gk_losses real,
    gk_clean_sheets real,
    gk_clean_sheets_pct real,
    gk_pens_att real,
    gk_pens_allowed real,
    gk_pens_saved real,
    gk_pens_missed real,
    gk_pens_save_pct real,
    player_id bigint CONSTRAINT players_id_not_null NOT NULL
);


--
-- Name: players_id_seq; Type: SEQUENCE; Schema: worldcup26; Owner: -
--

ALTER TABLE worldcup26.players ALTER COLUMN player_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME worldcup26.players_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);